version: 2
metrics:
  - name: unique_customer_count
    label: Unique customer count
    model: ref('customers')
    description: Total number of customers
    type: count_distinct
    sql: customer_id
    timestamp: created
    time_grains: [day, week, month, quarter, year]
  - name: completed_order_count
    label: Completed order count
    model: ref('orders')
    description: Total number of completed orders
    type: count_distinct
    sql: order_id
    timestamp: order_date
    time_grains: [day, week, month, quarter, year]
    filters:
      - field: is_completed
        operator: '='
        value: 'true'
  - name: dbt_expression
    label: dbt_expression
    description: derived metric in v1.2 ( deprecated )
    type: expression
    sql: "{{metric('unique_customer_count')}} / {{metric('unique_customer_count')}}"
    timestamp: created
    time_grains: [ day, week, month, quarter, year ]
  - name: dbt_derived
    label: dbt_derived
    calculation_method: derived
    expression: "{{metric('unique_customer_count')}} / {{metric('unique_customer_count')}}"
    timestamp: created
    time_grains: [ day, week, month, quarter, year ]
models:
  - name: customers
    description: >-
      This table has basic information about a customer, as well as some derived
      facts based on a customer's orders
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
        meta:
          metrics:
            lightdash_derived:
              type: number
              sql: "${unique_customer_count} / ${unique_customer_count}"
      - name: first_name
        description: Customer's first name. PII.
        meta:
          dimension:
            type: string
            urls:
              - label: "URL from value"
                url: "https://example.com/company/${value.formatted | url_encode }"
              - label: "URL from row value"
                url: "https://example.com/company/${row.customers.customer_id.raw | url_encode }"
              - label: "Invalid URL with bad reference"
                url: "https://example.com/company/${row.customer_id.raw | url_encode }"
      - name: last_name
        description: Customer's last name. PII.
      - name: created
        description: Timestamp (UTC) when customer was created
        meta:
          metrics:
            date_of_first_created_customer:
              type: min
            date_of_most_recent_created_customer:
              type: max
      - name: first_order
        description: Date of the customers first order
        meta:
          dimension:
            hidden: true
      - name: most_recent_order
        description: Date of the customers most recent order
        meta:
          dimension:
            hidden: true
      - name: days_since_last_order
        description: Number of days since the customers last order
        meta:
          dimension:
            hidden: true
      - name: days_between_created_and_first_order
        description: >-
          Number of days between the customer being created and making their
          first order
        meta:
          dimension:
            hidden: true
      - name: number_of_orders
        description: ""
        meta:
          dimension:
            hidden: true
      - name: customer_lifetime_value
        description: ""
        meta:
          dimension:
            hidden: true
  - name: orders
    description: >-
      This table has basic information about orders, as well as some derived
      facts based on payments
    meta:
      joins:
        - join: customers
          sql_on: ${customers.customer_id} = ${orders.customer_id}
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order
        meta:
          metrics:
            unique_order_count:
              type: count_distinct
      - name: is_completed
        description: Boolean indicating if status is completed
        meta:
          metrics:
            fulfillment_rate:
              type: average
              format: percent
              round: 1
              sql: CASE WHEN ${is_completed} THEN 1 ELSE 0 END
              show_underlying_values:
                - amount
                - customers.first_name
      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: order_date
        description: Date (UTC) that the order was placed
        meta:
          metrics:
            date_of_first_order:
              type: min
            date_of_most_recent_order:
              type: max
      - name: status
        description: "{{ doc(\"orders_status\") }}"
        tests:
          - accepted_values:
              values:
                - placed
                - shipped
                - completed
                - return_pending
                - returned
      - name: amount
        description: Total amount (USD) of the order
        tests:
          - not_null
        meta:
          metrics:
            average_order_size:
              type: average
              format: usd
              round: 2
            total_order_amount:
              type: sum
              format: usd
              round: 2
            total_completed_order_amount:
              type: sum
              format: usd
              round: 2
              filters:
                - is_completed: "true"
            total_non_completed_order_amount:
              type: number
              format: usd
              round: 2
              sql: ${total_order_amount}-${total_completed_order_amount}
          dimension:
            hidden: true
      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card
        tests:
          - not_null
        meta:
          dimension:
            hidden: true
      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon
        tests:
          - not_null
        meta:
          dimension:
            hidden: true
      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer
        tests:
          - not_null
        meta:
          dimension:
            hidden: true
      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
        tests:
          - not_null
        meta:
          dimension:
            hidden: true
  - name: payments
    description: This table has information about individual payments
    meta:
      joins:
        - join: orders
          sql_on: ${orders.order_id} = ${payments.order_id}
        - join: customers
          sql_on: ${customers.customer_id} = ${orders.customer_id}
    columns:
      - name: payment_id
        description: This is a unique identifier for a payment
        meta:
          metrics:
            unique_payment_count:
              type: count_distinct
              description: count of all payments
      - name: order_id
        description: Foreign key to the orders table
      - name: payment_method
        description: Method of payment used, for example credit card
      - name: amount
        description: Total amount (AUD) of the individual payment
        meta:
          metrics:
            total_revenue:
              type: sum
              description: Sum of all payments
